### ISSUE TITLE
Automatically teardown instances in CI

### ISSUE THREAD

**Issue by alexashley** [rode/rode-dev-env#3]
Originally I wanted this action to run `docker compose down` without the need for an additional clean up step, like this one:

```yaml
- name: Stop Rode Environment
  if: always()
  uses: rode/rode-dev-env@v0.1.0
  with:
   stage: 'post'
```

JavaScript actions support `main` and `post` hooks, where the `post` hooks runs when the job is completed. 

```yaml
runs:
  using: node12
  main: dist/index.js
  post: dist/index.js
```

The action needs to know where it's been checked out in CI, so that the right [path](https://github.com/rode/rode-dev-env/blob/c159f64c00e4723cc066624c6423bde4c80e00ab/src/docker-compose.js#L43) can be passed to docker compose and the [grafeas config](https://github.com/rode/rode-dev-env/blob/main/grafeas/config.yaml) mount is successful.

Part of the path to the directory where actions are checked out includes the reference (e.g., tag or branch), so while the path appears stable otherwise, the action has to know what version it is. 

As a result, I had to switch to a compose action in order to find the directory where the action was checked out, as that's the only way that `github.action_path` is actually set. 

Some ideas, ranked by preference:

- Use `esbuild` to bake the static files (`docker-compose.yaml`, `grafeas/config.yaml`) into the dist, then at runtime, write them to a temporary directory, stash the location with `core.saveState`, and then use the post hook to clean everything up
- Create a separate JS action and reference it from the composite action (I tried this with a local action, but may not have set it up correctly)
- Bake the current version into the bundled JS output and assume GitHub Actions never changes the path of checked out code
